@startuml
title Class Diagram RepositoryAnalysis

package myapp <<Folder>> {
  class init
}

package control <<Folder>> {
  class main
  class auth
}

package util <<Folder>> {
  class utilidades
  class manipula_arquivos
}

package services <<Folder>> {
  class repositorios
  class usuarios
}

package config <<Folder>> {
  class db
}

package database <<Database>> {
  class myappdb
}

package views <<Views>> {
  package m <<Folder>> {
    class listar
    class criar
    class analisado
  }

  package a <<Folder>> {
    class login
    class register
  }

}

init --> db
init --> main
init --> auth
db --> myappdb
main --> repositorios
repositorios --> db
main --> utilidades
utilidades --> manipula_arquivos
utilidades --> repositorios
auth --> usuarios
usuarios --> db
listar --> main 
criar --> main
analisado --> main
login --> auth 
register --> auth

@enduml