@startuml

title Class Diagram RepositoryAnalysis

package myapp <<Folder>> {
  class init
}

package control <<Folder>> {
  class main
  class auth
}

package util <<Folder>> {
  class utilidades
}

package services <<Folder>> {
  class repositorio
  class usuario
}

package config <<Folder>> {
  class db
}

package database <<Database>> {
  class myappdb
}


init --> db
init --> main
init --> auth
db --> myappdb
main --> repositorio
repositorio --> db
main --> utilidades
auth --> usuario
usuario --> db

@enduml