@startuml
actor       User as user
boundary    Principal as principal
control     Control.Main as main
control     Util.Utilidades as utilidades
entity      Service.Repositorio  as repositorio
queue       Queue as fila
database    Database as banco 

user -> principal : seleciona analisar
principal -> main : analisar repositorio(s) \n (Processar em Backgroud)
main -> main : checar repositorios(s) \n para analise
main -> main : consumidor dos repositorio(s)
    group Thread Consumidor
    main -> utilidades : disparar uma thread de \n acompanhamento (Consumidor)
    utilidades -> utilidades : cria thread para consumir \n elementos da fila
    utilidades -> fila : consome repositorio
        group Thread Analisar
            utilidades -> utilidades : cria nova thread para \n analisar repositorio
        end
        group Thread Acessa Banco
            utilidades -> utilidades : cria nova thread para \n atualizar status \n do repositorio no banco
            utilidades -> repositorio : atualiza status \n do repositorio
            repositorio -> banco : salva repositorio
            banco --> repositorio : resposta
            repositorio --> utilidades : resposta
        end 
        utilidades -> main : volta para o fluxo principal
    end
main --> principal : repositorio(s) analisados(s)
@enduml